server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.157.163.47:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&autoReconnect=true
    username: root
    password: FLq4OsTMyDzVOtmTL1yU
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  flyway:
    baseline-on-migrate: true
    table: scheme-version
    baseline-version: 0

mybatis:
  mapper-locations: classpath:mapping/*.xml     #mapper文件路径
  type-aliases-package: com.xiaoyao.mysq.linterceptor.demo.entity   #实体类的包路径

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
